server:
  port: 9000
spring:
  kafka:
    bootstrap-servers: ${kafka_bootstrap_servers:localhost:9092}
    #set access basic security (user,password) here
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${kafka_username:'admin'} password=${kafka_password:'admin-secret'};
        mechanism: PLAIN
      security:
        protocol: SASL_PLAINTEXT
    consumer:
      #must set group-id when group managed listener is used!
      group-id: group-id
    jaas:
      enabled: true
    listener:
      #When set manual acknowledgment, client must call acknowledgment.acknowledge(); to commit. Default is BATCH.
      ack-mode: manual_immediate